### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by MoriRo** [Albermonte/nimiq-shortener#24]
On iOS it always says:
Error: Already open in another tab or window.
I have tried four different browsers, changed to mobile network and I always have the same.

**Comment by Albermonte** [comment]
Which device and iOS version? Just tested on an iPhone 11 Pro iOS 13 in Safari and works

**Comment by MoriRo** [comment]
I use an iPhone 7 with the newest iOS version. Gesendet mit der WEB.DE Mail AppAm 29.04.20 um 20:48 schrieb Alberto Monterroso
                
            
            
                
                    Von: "Alberto Monterroso" <notifications@github.com>Datum: 29. April 2020An: Albermonte/nimiq-shortener <nimiq-shortener@noreply.github.com>Cc: Author <author@noreply.github.com>,MoriRo <hashtag-unbekannt@web.de>Betreff: Re: [Albermonte/nimiq-shortener] Not working on iOS (#24)
                
                
Which device and iOS version? Just tested on an iPhone 11 Pro iOS 13 in Safari and works

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Albermonte/nimiq-shortener/issues/24#issuecomment-621395280",
"url": "https://github.com/Albermonte/nimiq-shortener/issues/24#issuecomment-621395280",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MoriRo** [comment]
The same with the miner:


Von meinem iPhone gesendet

**Comment by Albermonte** [comment]
I've just tested again using an iPhone 7 iOS 12 and it's working for me, maybe you have nimiq.com or safe.nimiq.com or shortnim.me open in another tab?

![iPhone 7 iOS 12](https://user-images.githubusercontent.com/14013679/80954702-30504d00-8dfe-11ea-9ff0-3d983311d9a0.PNG)

**Comment by MoriRo** [comment]
Now it works 😅

**Comment by MoriRo** [comment]
Can you delete the complete conversation please?
