### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by superuser47890** [Albermonte/nimiq-shortener#25]
On the desktop version, I fill every box correctly then click Shorten It but nothing happens...

**Comment by Albermonte** [comment]
I've just tried and it's working, which information are you using to fill the boxes?

Can you share your OS (Windows 10, 7, MacOS, Linux...) and which browser are you using (Firefox, Chorme, Brave...)

There could be more info on the developer console, you can open it pressing F12 on most browsers.

A screenshot of the error and the page would be awesome

**Comment by superuser47890** [comment]
Hi. I tried it on Brave, but I have tried it on Chrome and it works fine. I should have used Chrome in the first place. Thank you.
