### ISSUE TITLE
Nimiq transition

### ISSUE THREAD

**Issue by vpts1202** [Albermonte/nimiq-shortener#39]
Hello [Albermonte](https://github.com/Albermonte) 

You have very good product. Since Coinhive shortener stopped many years ago, I was not able to find any similar to it.
 
The issue is that Nimiq is in transit from PoW to PoS.
Can you make the same product(shortener) for any other algos/coins, e.g. RandomX/Monero?

Thanks

**Comment by Albermonte** [comment]
I don't have any plan to continue supporting this since the rewards for mining in web are so low that is not worth it

**Comment by vpts1202** [comment]
Web mining was, is and will be. Its all depend on right algos/coins+right clients/miners(webmasters).

I looked at your projects here in github and I must say that you are a talented person.
Don't drop this focus/direction(web mining).

Thanks
