### ISSUE TITLE
url,OK!Three times no Nim was received

### ISSUE THREAD

**Issue by jackerfang** [Albermonte/nimiq-shortener#4]
url,ok!Three times no Nim was received

**Comment by Albermonte** [comment]
Can you explain it a little more? 

- Whats the problem?
- What were you doing?
- What did you expect to happen?

**Comment by Albermonte** [comment]
Payout are sended when the minimun of 1 NIM is reached, they are handled by https://sushipool.com/
You can check there the amount of NIM you have
